spring.application.name=backend
spring.datasource.url=jdbc:postgresql://cotidian-db:5432/cotidian
spring.datasource.username=cotidian
spring.datasource.password=database

# Driver do Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect